export interface Review {
  name: string;
  when: string;
  text: string;
}

/**
 * Google reviews for the Bubbles Auto Spa listing. GENERATED by scripts/fetch-reviews.mjs
 * from the Places API, do not hand-edit the numbers: run the script to refresh.
 * Review text is verbatim (whitespace normalised). Names are first name and last initial.
 */
export const REVIEWS = {
  heading: "What customers say",
  rating: 5,
  count: 280,
  asOf: "September 5, 2026",
  url: "https://maps.google.com/?cid=9324360744266123406",
  items: [
    {"name": "Jim B.", "when": "September 2026", "text": "Honestly blew me away. Took my vehicle to Bubbles Auto Spa and Cody got the paint looking better than the day I bought it. Super smooth finish and zero flaws left behind. Great guy to deal with, wouldn't take my car anywhere else."},
    {"name": "Nancy S.", "when": "September 2026", "text": "Bubbles Auto Spa detailed the inside of my car and it is like a brand new car inside. My car is seven years old and was grubby, but now like new. They were awesome and I recommend them. Price was very fair as well."},
    {"name": "Robert H.", "when": "August 2026", "text": "Brandon and his team did two of our vehicles last week and did an amazing job on both of them!"},
    {"name": "Gerald C.", "when": "August 2026", "text": "My truck looks great inside and out. Would recommend and will use again. Thank you."},
  ] as Review[],
} as const;
