#!/usr/bin/env node
/**
 * Refresh src/lib/reviews.ts from the Google Places API (legacy Place Details).
 *
 *   GOOGLE_PLACES_API_KEY=... node scripts/fetch-reviews.mjs
 *
 * Keeps the rating and review count honest (they are printed on the site) and
 * pulls the newest five-star reviews with real names and enough text. Review
 * text is kept verbatim apart from whitespace. Google requires attribution when
 * its reviews are shown, which the Reviews section provides.
 */
import { writeFileSync } from "node:fs";

const PLACE_ID = "ChIJq09ZOWCQUiwRjkiUv7HIZoE"; // Bubbles Auto Spa, 23525 Little Mack Ave
const key = process.env.GOOGLE_PLACES_API_KEY;
if (!key) {
  console.error("Set GOOGLE_PLACES_API_KEY");
  process.exit(1);
}

const fields = "name,rating,user_ratings_total,reviews,url";
const res = await fetch(
  `https://maps.googleapis.com/maps/api/place/details/json?place_id=${PLACE_ID}&fields=${fields}&reviews_sort=newest&key=${key}`
);
const json = await res.json();
if (json.status !== "OK") {
  console.error("Places API:", json.status, json.error_message || "");
  process.exit(1);
}
const r = json.result;

const emoji = /[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}]/u;
const shortName = (name) => {
  const parts = name.split(/\s+/).filter(Boolean);
  if (parts.length < 2 || parts.some((p) => p.length < 2)) return null;
  const first = parts[0] === parts[0].toUpperCase() ? parts[0][0] + parts[0].slice(1).toLowerCase() : parts[0];
  return `${first} ${parts[parts.length - 1][0].toUpperCase()}.`;
};
const monthYear = (t) => new Date(t * 1000).toLocaleDateString("en-US", { month: "long", year: "numeric", timeZone: "UTC" });

const items = [];
for (const rv of r.reviews || []) {
  if ((rv.rating || 0) < 5) continue;
  const text = (rv.text || "").replace(/\s+/g, " ").trim();
  if (text.length < 40 || emoji.test(text)) continue;
  const name = shortName(rv.author_name || "");
  if (!name) continue;
  items.push({ name, when: monthYear(rv.time), text });
}

const asOf = new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" });
let out = "export interface Review {\n  name: string;\n  when: string;\n  text: string;\n}\n\n";
out +=
  "/**\n * Google reviews for the Bubbles Auto Spa listing. GENERATED by scripts/fetch-reviews.mjs\n * from the Places API, do not hand-edit the numbers: run the script to refresh.\n * Review text is verbatim (whitespace normalised). Names are first name and last initial.\n */\n";
out += `export const REVIEWS = {\n  heading: "What customers say",\n  rating: ${r.rating},\n  count: ${r.user_ratings_total},\n  asOf: ${JSON.stringify(asOf)},\n  url: ${JSON.stringify(r.url)},\n  items: [\n`;
for (const it of items) out += `    ${JSON.stringify(it)},\n`;
out += "  ] as Review[],\n} as const;\n";
writeFileSync(new URL("../src/lib/reviews.ts", import.meta.url), out);
console.log(`reviews.ts: ${r.rating} from ${r.user_ratings_total} reviews, ${items.length} quotes`);
